# 服务器配置
server:
  port: 9090

# http 客户端配置
http-client:
  connect-timeout: 20 # 连接超时超时
  read-timeout: 120 # 读取数据超时时间
  debug: false # 使用自定义的客户端是否输出请求结果

# log 级别
logging:
  level:
    com.sitech.bdvo.api.server: debug